services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile-rest
      target: final
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'

  orchestrator:
    build:
      context: ./
      dockerfile: Dockerfile-orchestrator
      target: final
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '666:666'

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
        - '5432:5432' # TODO: delete this line in production
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  minio_data:
    driver: local